apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub-ml-workshop
#  namespace: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-seldon/cluster
      name: odhseldon
    - kustomizeConfig:
        overlays:
          - custom-image
        parameters:
          - name: s3_endpoint_url
            value: "minio-ml-workshop.ml-workshop:9000"
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          # - cuda
          # - cuda-11.0.3
          - additional
          # - custom-image
          # - custom-extensions
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        overlays:
          - custom-image
        parameters:
          - name: OCP_APPS_URI
          # Change the line below to match your cluster URI. Using the URI from your OpenShift cluster,
          # copy everything from .apps onwards and replace the value below.
            value: .apps.cluster-x5xvd.x5xvd.sandbox320.opentlc.com
        repoRef:
          name: manifests
          path: ml-workshop-airflow2
      name: airflow2
    - kustomizeConfig:
        overlay:
          - custom-image
        repoRef:
          name: manifests
          path: ml-workshop-mlflow
      name: ml-workshop-mlflow
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ml-workshop-minio
      name: minio     
  repos:
    - name: kf-manifests
      uri: https://github.com/kubeflow/manifests/archive/v1.2-branch.tar.gz
    - name: manifests
      uri: https://github.com/masoodfaisal/odh-manifests/tarball/disconnected-install
  version: disconnected-install
